# Generated by Django 4.2.7 on 2026-04-05 09:41

from django.db import migrations, models
import sessions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=sessions.models.generate_code, max_length=6, unique=True)),
                ('host', models.IntegerField()),
                ('mode', models.CharField(choices=[('interview', 'Interview'), ('meeting', 'Meeting')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
    ]
